#!/bin/sh
#
# openstack-heat-api-cfn - Openstack Heat CFN-compatible API Service
#
# chkconfig:   - 98 02
# description: Provides an AWS CloudFormation-compatible interface to the Heat
#              Engine for starting AWS CloudFormation templates on OpenStack.
#

### BEGIN INIT INFO
# Provides:
# Required-Start: $remote_fs $network $syslog
# Required-Stop: $remote_fs $syslog
# Default-Stop: 0 1 6
# Short-Description: OpenStack Heat CFN-compatible API Server
# Description: The Heat API provides an OpenStack-native
#              ReST API to the Heat Engine for starting
#              AWS CloudFormation templates on OpenStack.
### END INIT INFO

. /etc/rc.d/init.d/functions

prog=openstack-heat-api-cfn
exec="/usr/bin/heat-api-cfn"
config="/etc/heat/heat.conf"
pidfile="/var/run/heat/$prog.pid"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/openstack-heat-api-cfn

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    daemon --user heat --pidfile $pidfile "$exec &>/dev/null & echo \$! > $pidfile"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
